# .readthedocs.yaml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - doxygen
    - graphviz
    - make
  jobs:
    pre_build:
      - echo "Pre build"
      - echo "Cleaning..."
      - make clean_all
      - echo "Doxygen..."
      - make doxygen
      - echo "Api generation..."
      - make api_generator
      - echo "Readme sync..."
      - make readme_sync

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt    