# sync_rtd_docs.py
import re
import os
from pathlib import Path

# --- CONFIGURACIÓN GLOBAL DEL SCRIPT ---
README_FILE_PATH = "README.rst"  # Ruta al README principal
DOCS_BASE_DIR = "docs"          # Directorio base donde se generan los archivos .rst
INDEX_FILE_PATH = os.path.join(DOCS_BASE_DIR, "index.rst") # Archivo principal del toctree

# Marcadores para la sección autogenerada del toctree
TOC_START_MARKER = ".. AUTOGENERATED-TOC-START"
TOC_END_MARKER = ".. AUTOGENERATED-TOC-END"
# --- FIN DE LA CONFIGURACIÓN ---

# Expresión regular para parsear la directiva rtd-sync-config
# Captura el bloque de la directiva y sus opciones :key: value
DIRECTIVE_RE = re.compile(
    r"^\.\.\s+rtd-sync-config::\s*\n"  # Inicio de la directiva
    r"((?:\s+:[a-zA-Z0-9_-]+:.*?\n)+)"  # Bloque de opciones (una o más)
    , re.MULTILINE
)
OPTION_RE = re.compile(r"^\s+:([a-zA-Z0-9_-]+):\s*(.*?)\s*$", re.MULTILINE)

# Expresión regular para encontrar cabeceras de sección RST
SECTION_HEADER_RE = re.compile(
    r"^(?P<title_text>.+)\n"
    r"(?P<underline_char>[=\-`:'\"~^_*#.+])(?P=underline_char){2,}\n",
    re.MULTILINE
)

def parse_readme_for_sync_blocks(readme_content):
    """
    Parsea el contenido del README.rst para encontrar bloques rtd-sync-config
    y las secciones RST asociadas.
    Devuelve una lista de diccionarios, cada uno representando un bloque a procesar.
    """
    sync_blocks = []
    last_pos = 0

    # Iterar sobre todas las directivas encontradas
    for directive_match in DIRECTIVE_RE.finditer(readme_content):
        directive_text = directive_match.group(0)
        options_text = directive_match.group(1)
        
        config = {}
        for opt_match in OPTION_RE.finditer(options_text):
            key = opt_match.group(1).strip()
            value = opt_match.group(2).strip()
            if key == "skip": # :skip: es un booleano implícito
                config[key] = True
            else:
                config[key] = value
        
        # Buscar la cabecera de sección que sigue inmediatamente a la directiva
        # La búsqueda de la cabecera empieza después de la directiva actual
        header_search_start_pos = directive_match.end()
        section_header_match = SECTION_HEADER_RE.search(readme_content, pos=header_search_start_pos)
        
        if not section_header_match:
            print(f"  [WARN] Directiva en la posición {directive_match.start()} no está seguida por una cabecera de sección válida. Saltando.")
            continue

        # Asegurarse de que no haya otra directiva entre la actual y la cabecera
        # Esto es para evitar que una directiva "flotante" capture una sección lejana.
        # Buscamos otra directiva entre el final de la actual y el inicio de la cabecera encontrada.
        next_directive_search_region = readme_content[directive_match.end():section_header_match.start()]
        if DIRECTIVE_RE.search(next_directive_search_region):
            print(f"  [WARN] Directiva en la posición {directive_match.start()} parece tener otra directiva antes de su sección. Saltando esta instancia.")
            continue

        section_title = section_header_match.group('title_text').strip()
        section_content_start_pos = section_header_match.end()

        # Encontrar el final del contenido de esta sección
        # (inicio de la siguiente sección/directiva o final del archivo)
        next_element_search_pos = section_content_start_pos
        
        # Buscar la siguiente cabecera de sección
        next_section_header_match = SECTION_HEADER_RE.search(readme_content, pos=next_element_search_pos)
        # Buscar la siguiente directiva rtd-sync-config
        next_directive_match = DIRECTIVE_RE.search(readme_content, pos=next_element_search_pos)

        content_ends_at = len(readme_content) # Por defecto, hasta el final del archivo

        if next_section_header_match and next_directive_match:
            # Si hay ambas, tomar la que aparece primero
            content_ends_at = min(next_section_header_match.start(), next_directive_match.start())
        elif next_section_header_match:
            content_ends_at = next_section_header_match.start()
        elif next_directive_match:
            content_ends_at = next_directive_match.start()
            
        section_body = readme_content[section_content_start_pos:content_ends_at].strip()

        sync_blocks.append({
            "config": config,
            "readme_title": section_title,
            "readme_content_body": section_body,
            "directive_text": directive_text # Para depuración o logging
        })
        last_pos = content_ends_at # Actualizar para la siguiente búsqueda

    return sync_blocks


def generate_or_update_rst_file(block_info):
    """
    Genera o actualiza un archivo .rst basado en la información del bloque.
    """
    config = block_info["config"]

    if config.get("skip", False):
        print(f"  -> Sección '{block_info['readme_title']}' marcada con :skip:. Saltando generación de archivo.")
        return None # No se genera archivo, no hay ruta para el toctree

    target_rel_path = config.get("target")
    if not target_rel_path:
        print(f"  [ERROR] Sección '{block_info['readme_title']}' no tiene :target: y no está marcada con :skip:. No se puede generar archivo.")
        return None

    # Asegurarse de que la ruta del target sea relativa al DOCS_BASE_DIR si no lo es ya
    if not target_rel_path.startswith(DOCS_BASE_DIR + os.sep) and not Path(target_rel_path).is_absolute():
        target_abs_path = Path(DOCS_BASE_DIR) / target_rel_path
    else:
        target_abs_path = Path(target_rel_path) # Asume que ya incluye DOCS_BASE_DIR o es absoluta

    # Crear directorios si no existen
    target_abs_path.parent.mkdir(parents=True, exist_ok=True)

    title_in_doc = config.get("title_in_doc", block_info["readme_title"])
    content_body = block_info["readme_content_body"]

    # Crear el contenido del archivo .rst
    # Usar '=' para el subrayado del título principal del archivo
    underline_char = "="
    title_line = title_in_doc
    underline_line = underline_char * len(title_line)

    file_content = f"{title_line}\n{underline_line}\n\n{content_body}\n"

    try:
        # Comprobar si el contenido ha cambiado para evitar escrituras innecesarias
        existing_content = ""
        if target_abs_path.exists():
            with open(target_abs_path, 'r', encoding='utf-8') as f_read:
                existing_content = f_read.read()
        
        if existing_content.strip() == file_content.strip():
            print(f"  -> Contenido para '{target_abs_path}' no ha cambiado. No se necesita escribir.")
        else:
            with open(target_abs_path, 'w', encoding='utf-8') as f_write:
                f_write.write(file_content)
            print(f"  -> Archivo '{target_abs_path}' generado/actualizado para la sección '{block_info['readme_title']}'.")
        return target_rel_path # Devuelve la ruta relativa usada para el toctree
    except IOError as e:
        print(f"  [ERROR] Al escribir en '{target_abs_path}': {e}")
        return None


def update_toctree(index_file_path_str, toc_entries_data):
    """
    Actualiza la sección del toctree en el archivo index.
    toc_entries_data es una lista de tuplas (toctree_text, target_file_path_for_toctree)
    """
    index_file_path = Path(index_file_path_str)
    if not index_file_path.exists():
        print(f"[ERROR] Archivo de índice '{index_file_path}' no encontrado. No se puede actualizar el toctree.")
        return

    try:
        with open(index_file_path, 'r', encoding='utf-8') as f:
            original_index_content = f.read()
    except IOError as e:
        print(f"[ERROR] Al leer el archivo de índice '{index_file_path}': {e}")
        return

    toc_start_idx = original_index_content.find(TOC_START_MARKER)
    toc_end_idx = original_index_content.find(TOC_END_MARKER)

    if toc_start_idx == -1 or toc_end_idx == -1 or toc_end_idx <= toc_start_idx:
        print(f"[ERROR] Marcadores '{TOC_START_MARKER}' y/o '{TOC_END_MARKER}' no encontrados o mal posicionados en '{index_file_path}'.")
        print("        Asegúrate de que ambos marcadores existen y están en el orden correcto.")
        return

    # Preservar la parte antes del inicio del TOC autogenerado
    prefix = original_index_content[:toc_start_idx + len(TOC_START_MARKER)]
    
    # Preservar la parte después del final del TOC autogenerado
    # Se busca desde el final del marcador TOC_END_MARKER
    suffix_start_pos = toc_end_idx
    suffix = original_index_content[suffix_start_pos:] # Incluye el TOC_END_MARKER

    # Intentar extraer :maxdepth: y :caption: del toctree existente si hay uno
    # Esto es una simplificación, un parseo más robusto sería mejor
    existing_toctree_block = original_index_content[toc_start_idx:toc_end_idx]
    maxdepth_match = re.search(r":maxdepth:\s*(\d+)", existing_toctree_block)
    caption_match = re.search(r":caption:\s*(.+?)\n", existing_toctree_block) # Captura hasta el fin de línea
    
    maxdepth_option = f"   :maxdepth: {maxdepth_match.group(1) if maxdepth_match else 2}"
    caption_option = f"   :caption: {caption_match.group(1).strip() if caption_match else 'Contenido Autogenerado'}"

    # Construir el nuevo bloque de toctree
    new_toctree_lines = [".. toctree::", maxdepth_option, caption_option, ""] # Línea vacía
    for _, target_path_for_toc in toc_entries_data:
        if target_path_for_toc:
            # La ruta para el toctree no debe tener la extensión .rst
            # y debe ser relativa al directorio que contiene el index.rst
            
            # Primero, hacerla relativa a DOCS_BASE_DIR si no lo es
            if target_path_for_toc.startswith(DOCS_BASE_DIR + os.sep):
                path_relative_to_docs_base = target_path_for_toc[len(DOCS_BASE_DIR + os.sep):]
            else: # Si ya es relativa dentro de docs o algo así
                path_relative_to_docs_base = target_path_for_toc

            entry_path = Path(path_relative_to_docs_base).with_suffix('') # Quitar .rst
            new_toctree_lines.append(f"   {entry_path.as_posix()}") # Usar / como separador

    new_toctree_block = "\n".join(new_toctree_lines)
    
    # Ensamblar el contenido final del index
    updated_index_content = f"{prefix}\n\n{new_toctree_block}\n\n{suffix}"
    
    if original_index_content.strip() == updated_index_content.strip():
        print(f"  -> Toctree en '{index_file_path}' no ha cambiado. No se necesita escribir.")
    else:
        try:
            with open(index_file_path, 'w', encoding='utf-8') as f:
                f.write(updated_index_content)
            print(f"  -> Toctree en '{index_file_path}' actualizado.")
        except IOError as e:
            print(f"[ERROR] Al escribir el archivo de índice actualizado '{index_file_path}': {e}")


def main():
    readme_path = Path(README_FILE_PATH)
    if not readme_path.exists():
        print(f"[ERROR] Archivo README '{README_FILE_PATH}' no encontrado.")
        return

    print(f"Leyendo '{README_FILE_PATH}'...")
    try:
        with open(readme_path, 'r', encoding='utf-8') as f:
            readme_content = f.read()
    except IOError as e:
        print(f"[ERROR] Al leer '{README_FILE_PATH}': {e}")
        return

    print("Parseando README en busca de directivas 'rtd-sync-config'...")
    sync_blocks = parse_readme_for_sync_blocks(readme_content)

    if not sync_blocks:
        print("No se encontraron bloques 'rtd-sync-config' para procesar.")
        return

    print(f"Se encontraron {len(sync_blocks)} bloques de sincronización.")
    
    processed_files_for_toctree = [] # Lista de (toctree_entry_text, target_file_path)

    Path(DOCS_BASE_DIR).mkdir(parents=True, exist_ok=True) # Asegurar que el dir docs existe

    for i, block in enumerate(sync_blocks):
        print(f"\nProcesando bloque {i+1}/{len(sync_blocks)} (Sección README: '{block['readme_title']}')")
        
        if block["config"].get("skip", False):
            print(f"  -> Sección '{block['readme_title']}' marcada con :skip:. Saltando.")
            continue # No se procesa, no va al toctree

        generated_target_path = generate_or_update_rst_file(block)
        
        if generated_target_path:
            # Determinar el texto para el toctree
            toctree_text = block["config"].get("toctree_entry")
            if not toc_text: # Si :toctree_entry: no está o está vacío
                toctree_text = block["config"].get("title_in_doc", block["readme_title"])
            
            # Solo añadir al toctree si hay un target y no está explícitamente vacío
            if block["config"].get("toctree_entry", "DEFAULT_VALUE_IF_MISSING") != "": # Si existe y no es ""
                 processed_files_for_toctree.append((toctree_text, generated_target_path))


    if processed_files_for_toctree:
        print(f"\nActualizando toctree en '{INDEX_FILE_PATH}'...")
        update_toctree(INDEX_FILE_PATH, processed_files_for_toctree)
    else:
        print(f"\nNo se generaron archivos para incluir en el toctree o todas las entradas de toctree_entry estaban vacías.")

    print("\n--- Sincronización completada ---")

if __name__ == "__main__":
    main()