# sync_rtd_docs.py
import re
import os
from pathlib import Path

# --- CONFIGURACIÓN GLOBAL DEL SCRIPT ---
README_FILE_PATH = "README.rst"  # Ruta al README principal
DOCS_BASE_DIR = "docs"          # Directorio base donde se generan los archivos .rst
# Asegurarse de que INDEX_FILE_PATH usa la ruta correcta, asumiendo que está dentro de DOCS_BASE_DIR/source
# Si tu index.rst está en docs/source/index.rst, esta es la configuración:
INDEX_FILE_PATH = os.path.join(DOCS_BASE_DIR, "source", "index.rst") # Archivo principal del toctree

# Marcadores para la sección autogenerada del toctree
TOC_START_MARKER = ".. AUTOGENERATED-TOC-START"
TOC_END_MARKER = ".. AUTOGENERATED-TOC-END"
# --- FIN DE LA CONFIGURACIÓN ---

# Expresión regular para parsear la directiva rtd-sync-config
# Captura el bloque de la directiva y sus opciones :key: value
DIRECTIVE_RE = re.compile(
    r"^\.\.\s*\n"  # La línea inicial ".." seguida de un salto de línea
    r"\s+rtd-sync-config::\s*\n"  # La línea "rtd-sync-config::" indentada
    r"((?:\s+:[a-zA-Z0-9_-]+:.*?\n)+)"  # Bloque de opciones, también indentadas
    , re.MULTILINE
)
OPTION_RE = re.compile(r"^\s+:([a-zA-Z0-9_-]+):\s*(.*?)\s*$", re.MULTILINE)

# Expresión regular para encontrar cabeceras de sección RST
SECTION_HEADER_RE = re.compile(
    r"^(?P<title_text>.+)\n"
    r"(?P<underline_char>[=\-`:'\"~^_*#.+])(?P=underline_char){2,}\n",
    re.MULTILINE
)

def parse_readme_for_sync_blocks(readme_content):
    """
    Parsea el contenido del README.rst para encontrar bloques rtd-sync-config
    y las secciones RST asociadas.
    Devuelve una lista de diccionarios, cada uno representando un bloque a procesar.
    """
    sync_blocks = []
    # last_pos = 0  # Variable no usada, se puede eliminar

    # Iterar sobre todas las directivas encontradas
    for directive_match in DIRECTIVE_RE.finditer(readme_content):
        # directive_text = directive_match.group(0)  # Variable no usada, se puede eliminar
        options_text = directive_match.group(1)
        
        config = {}
        for opt_match in OPTION_RE.finditer(options_text):
            key = opt_match.group(1).strip()
            value = opt_match.group(2).strip()
            if key == "skip": # :skip: es un booleano implícito
                config[key] = True
            else:
                config[key] = value
        
        header_search_start_pos = directive_match.end()
        section_header_match = SECTION_HEADER_RE.search(readme_content, pos=header_search_start_pos)
        
        if not section_header_match:
            print(f"  [WARN] Directiva en la posición {directive_match.start()} no está seguida por una cabecera de sección válida. Saltando.")
            continue

        next_directive_search_region = readme_content[directive_match.end():section_header_match.start()]
        if DIRECTIVE_RE.search(next_directive_search_region):
            print(f"  [WARN] Directiva en la posición {directive_match.start()} parece tener otra directiva antes de su sección. Saltando esta instancia.")
            continue

        section_title = section_header_match.group('title_text').strip()
        section_content_start_pos = section_header_match.end()

        next_element_search_pos = section_content_start_pos
        next_section_header_match = SECTION_HEADER_RE.search(readme_content, pos=next_element_search_pos)
        next_directive_match = DIRECTIVE_RE.search(readme_content, pos=next_element_search_pos)

        content_ends_at = len(readme_content)

        if next_section_header_match and next_directive_match:
            content_ends_at = min(next_section_header_match.start(), next_directive_match.start())
        elif next_section_header_match:
            content_ends_at = next_section_header_match.start()
        elif next_directive_match:
            content_ends_at = next_directive_match.start()
            
        section_body = readme_content[section_content_start_pos:content_ends_at].strip()

        sync_blocks.append({
            "config": config,
            "readme_title": section_title,
            "readme_content_body": section_body,
            # "directive_text": directive_text  # Variable no usada, se puede eliminar
        })
        # last_pos = content_ends_at  # Variable no usada, se puede eliminar

    return sync_blocks


def generate_or_update_rst_file(block_info):
    """
    Genera o actualiza un archivo .rst basado en la información del bloque.
    Devuelve la ruta relativa del archivo generado (respecto a la raíz del proyecto)
    o None si no se generó/actualizó.
    """
    config = block_info["config"]

    if config.get("skip", False):
        print(f"  -> Sección '{block_info['readme_title']}' marcada con :skip:. Saltando generación de archivo.")
        return None

    target_path_from_config = config.get("target")
    if not target_path_from_config:
        print(f"  [ERROR] Sección '{block_info['readme_title']}' no tiene :target: y no está marcada con :skip:. No se puede generar archivo.")
        return None

    # La ruta en :target: se espera que sea relativa a la raíz del proyecto,
    # por ejemplo, "docs/source/readme/about_petgem.rst"
    target_abs_path = Path(target_path_from_config).resolve()  # Resuelve a ruta absoluta

    # Crear directorios si no existen
    target_abs_path.parent.mkdir(parents=True, exist_ok=True)

    title_in_doc = config.get("title_in_doc", block_info["readme_title"])
    content_body = block_info["readme_content_body"]

    underline_char = "="
    title_line = title_in_doc
    underline_line = underline_char * len(title_line)
    file_content = f"{title_line}\n{underline_line}\n\n{content_body}\n"

    try:
        existing_content = ""
        if target_abs_path.exists():
            with open(target_abs_path, 'r', encoding='utf-8') as f_read:
                existing_content = f_read.read()
        
        if existing_content.strip() == file_content.strip():
            print(f"  -> Contenido para '{target_abs_path}' no ha cambiado. No se necesita escribir.")
        else:
            with open(target_abs_path, 'w', encoding='utf-8') as f_write:
                f_write.write(file_content)
            print(f"  -> Archivo '{target_abs_path}' generado/actualizado para la sección '{block_info['readme_title']}'.")
        # Devolver la ruta original de la config, ya que esta es la que se usará para el toctree
        # (relativa a la raíz, y el toctree la ajustará)
        return target_path_from_config
    except IOError as e:
        print(f"  [ERROR] Al escribir en '{target_abs_path}': {e}")
        return None

def extract_toctree_config(sync_blocks):
    """
    Extrae la configuración del toctree de los bloques de sincronización.
    Devuelve una lista de tuplas (toctree_text, target_path_from_config).
    """
    toctree_entries = []
    for block in sync_blocks:
        # Obtener el valor de :toctree_entry: de la configuración del bloque
        toctree_entry_value = block["config"].get("toctree_entry")
        
        # Determinar el texto para el toctree.  Si :toctree_entry: no está, usar :title_in_doc: o el título del README.
        final_toctree_text = None
        if toctree_entry_value is None:
            final_toctree_text = block["config"].get("title_in_doc", block["readme_title"])
        elif toctree_entry_value != "":
            final_toctree_text = toctree_entry_value
        
        if final_toctree_text: # Solo añadir al toctree si tenemos un texto válido.
            target_path_from_config = generate_or_update_rst_file(block)
            if target_path_from_config: # Agregado para que solo se agreguen archivos generados
                toctree_entries.append((final_toctree_text, target_path_from_config))
    return toctree_entries

def update_toctree(index_file_path_str, toc_entries_data):
    """
    Actualiza la sección del toctree en el archivo index.
    toc_entries_data es una lista de tuplas (toctree_text, target_file_path_from_config)
    target_file_path_from_config es la ruta tal como se especificó en :target:
    (ej. "docs/source/readme/about_petgem.rst")
    """
    index_file_path_obj = Path(index_file_path_str).resolve()
    if not index_file_path_obj.exists():
        print(f"[ERROR] Archivo de índice '{index_file_path_obj}' no encontrado. No se puede actualizar el toctree.")
        return

    try:
        with open(index_file_path_obj, 'r', encoding='utf-8') as f:
            original_index_content = f.read()
    except IOError as e:
        print(f"[ERROR] Al leer el archivo de índice '{index_file_path_obj}': {e}")
        return

    toc_start_idx = original_index_content.find(TOC_START_MARKER)
    toc_end_idx = original_index_content.find(TOC_END_MARKER)

    if toc_start_idx == -1 or toc_end_idx == -1 or toc_end_idx <= toc_start_idx:
        print(f"[ERROR] Marcadores '{TOC_START_MARKER}' y/o '{TOC_END_MARKER}' no encontrados o mal posicionados en '{index_file_path_obj}'.")
        print("        Asegúrate de que ambos marcadores existen y están en el orden correcto.")
        return

    prefix = original_index_content[:toc_start_idx + len(TOC_START_MARKER)]
    suffix = original_index_content[toc_end_idx:] 

    existing_toctree_block = original_index_content[toc_start_idx:toc_end_idx]
    maxdepth_match = re.search(r":maxdepth:\s*(\d+)", existing_toctree_block)
    caption_match = re.search(r":caption:\s*(.+?)\n", existing_toctree_block)
    
    maxdepth_option = f"   :maxdepth: {maxdepth_match.group(1) if maxdepth_match else 2}"
    caption_option = f"   :caption: {caption_match.group(1).strip() if caption_match else 'Contenido Autogenerado'}"

    new_toctree_lines = [".. toctree::", maxdepth_option, caption_option, ""]
    
    # El directorio que contiene el index.rst es la base para las rutas relativas en el toctree
    index_dir = index_file_path_obj.parent

    for _, target_path_str_from_config in toc_entries_data: # target_path_str_from_config es como "docs/source/readme/file.rst"
        if target_path_str_from_config:
            # Convertir la ruta del target (que es relativa a la raíz del proyecto)
            # a una ruta relativa al directorio del index.rst
            target_abs_path = Path(target_path_str_from_config).resolve()
            try:
                path_relative_to_index_dir = os.path.relpath(target_abs_path, index_dir)
            except ValueError: # Si están en diferentes unidades en Windows
                print(f"  [WARN] No se pudo calcular la ruta relativa para '{target_abs_path}' desde '{index_dir}'. Usando ruta original.")
                path_relative_to_index_dir = target_path_str_from_config # Fallback, puede no ser ideal

            entry_path = Path(path_relative_to_index_dir).with_suffix('') # Quitar .rst
            new_toctree_lines.append(f"   {entry_path.as_posix()}")

    new_toctree_block = "\n".join(new_toctree_lines)
    updated_index_content = f"{prefix}\n\n{new_toctree_block}\n\n{suffix}"
    
    if original_index_content.strip() == updated_index_content.strip():
        print(f"  -> Toctree en '{index_file_path_obj}' no ha cambiado. No se necesita escribir.")
    else:
        try:
            with open(index_file_path_obj, 'w', encoding='utf-8') as f:
                f.write(updated_index_content)
            print(f"  -> Toctree en '{index_file_path_obj}' actualizado.")
        except IOError as e:
            print(f"[ERROR] Al escribir el archivo de índice actualizado '{index_file_path_obj}': {e}")


def main():
    readme_path_obj = Path(README_FILE_PATH).resolve()
    if not readme_path_obj.exists():
        print(f"[ERROR] Archivo README '{readme_path_obj}' no encontrado.")
        return

    print(f"Leyendo '{readme_path_obj}'...")
    try:
        with open(readme_path_obj, 'r', encoding='utf-8') as f:
            readme_content = f.read()
    except IOError as e:
        print(f"[ERROR] Al leer '{readme_path_obj}': {e}")
        return

    print("Parseando README en busca de directivas 'rtd-sync-config'...")
    sync_blocks = parse_readme_for_sync_blocks(readme_content)

    if not sync_blocks:
        print("No se encontraron bloques 'rtd-sync-config' para procesar.")
        return

    print(f"Se encontraron {len(sync_blocks)} bloques de sincronización.")

    # --- NUEVO: Separar la extracción de la configuración del toctree ---
    #  Esta función también llama a generate_or_update_rst_file
    toc_entries_data = extract_toctree_config(sync_blocks)
    # --- FIN DEL NUEVO BLOQUE ---
    

    if toc_entries_data: #  Usar la variable ya calculada
        print(f"\nActualizando toctree en '{INDEX_FILE_PATH}'...")
        update_toctree(INDEX_FILE_PATH, toc_entries_data)
    else:
        print(f"\nNo se generaron archivos para incluir en el toctree o todas las entradas de :toctree_entry: estaban vacías/omitidas.")

    print("\n--- Sincronización completada ---")

if __name__ == "__main__":
    main()